### PR TITLE
call site.main() to prevent import error on Odoo.sh

### PR DESCRIPTION
**Pull request by zachwaite**
see issue #3

### CODE REVIEW

**Comment by lmignon** [comment]
@zachwaite How do you install extendable-pydantic in odoo.sh? From sources?

**Comment by lmignon** [comment]
superseded by #8

**Comment by zachwaite** [comment]
> @zachwaite How do you install extendable-pydantic in odoo.sh? From sources?

@lmignon yes, I added `extendable-pydantic @ git+https://github.com/zachwaite/extendable-pydantic.git@master` to requirements.txt in the odoo.sh project. IIRC at the time of the issue, extendable-pydantic was being installed automatically by Odoo.sh for some reason.

**Comment by lmignon** [comment]
Thank you for the patch. It's released in the new version 1.0.0 of the lib.
This new version is for pydantic V2. If you need it for pydantic V1 I can
make a new release 0.0.x

**Pull request closed without merging**
